// <auto-generated />
namespace WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_020));
        
        string IMigrationMetadata.Id
        {
            get { return "201303252008443_update_020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
