// <auto-generated />
namespace WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_021));
        
        string IMigrationMetadata.Id
        {
            get { return "201303262047474_update_021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
